
package ptts.gui.driver;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ptts.entities.CheckIn;
import ptts.entities.Driver;
import ptts.entities.Ticket;
import ptts.entities.Token;
import ptts.entities.managers.TicketManager;
import ptts.entities.managers.TokenManager;
import ptts.gui.LogoutConfirm;
import static ptts.main.PublicTransportTicketingSystem.driverController;
import ptts.services.TokenValidator;

/**
 *
 * @author Siri@MnS
 */
public class DriverTerminal extends javax.swing.JFrame {

    /**
     * Creates new form DriverTerminal
     */
    //public static JFrame driverTerminal = new DriverTerminal();
    public static JFrame driverTerminal;
    
    private static JFrame checkOutForm;
    private Driver currentDriver;
    
    private Token currentToken;
    private Ticket currentTicket;
    private String currentStation;
    //private float distance;
    
    public DriverTerminal() {
        initComponents();
        setLocationRelativeTo(null); //centering the JFrame in the computer display
        hide_panels();
        
        currentDriver = driverController.getCurrentDriver();
        
        populate_homescreen_panel();
        homescreen_panel.setVisible(true);
    }

    private void hide_panels(){
        homescreen_panel.setVisible(false);
        profile_edit_panel.setVisible(false);
        profile_panel.setVisible(false);
        checkout_panel.setVisible(false);
    }
    
    private void populate_homescreen_panel(){
        label_homescreen_currentUsername.setText(currentDriver.getName());
        label_homescreen_driverID.setText(currentDriver.getUserID());
        loadTokenList();
        label_homescreen_tokenStatus.setVisible(false);
        jCheckBox1.setSelected(!TokenValidator.status);
        
    }
    
    private void loadTokenList(){
        ArrayList<Token> tempTokenList = TokenManager.getTokenList();

        if (tempTokenList != null) {
            String[] tokenIDList = new String[tempTokenList.size()];
            for (int i = 0; i < tempTokenList.size(); i++) {
                tokenIDList[i] = tempTokenList.get(i).getTokenID();
            }
            
            combo_homescreen_tokenIDList.setModel(new DefaultComboBoxModel(tokenIDList));
            
            
        }
        else{
            String[] tokenIDList = {"Empty List"};
            combo_homescreen_tokenIDList.setModel(new DefaultComboBoxModel(tokenIDList));
            button_homescreen_validate.setEnabled(false);
        }
    }
    
    private void loadActiveTicketList(){
        ArrayList<Ticket> tempTicketList = currentToken.getActiveTicketList();

        if (tempTicketList != null && tempTicketList.size() != 0) {
            String[] ticketList = new String[tempTicketList.size()];
            for (int i = 0; i < tempTicketList.size(); i++) {
                ticketList[i] = tempTicketList.get(i).getTicketID();
            }
            
            combo_homescreen_ticketIDList.setModel(new DefaultComboBoxModel(ticketList));
            button_homescreen_validate.setEnabled(true);
            
        }
        else{
            String[] tokenIDList = {"Empty List"};
            combo_homescreen_ticketIDList.setModel(new DefaultComboBoxModel(tokenIDList));
            button_homescreen_validate.setEnabled(false);
            label_homescreen_tokenStatus.setText("Empty Token");
            label_homescreen_tokenStatus.setForeground(Color.RED);
            label_homescreen_tokenStatus.setFont(label_homescreen_tokenStatus.getFont().deriveFont(5));
            label_homescreen_tokenStatus.setVisible(true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homescreen_panel = new javax.swing.JPanel();
        button_homescreen_logout = new javax.swing.JButton();
        button_homescreen_profile = new javax.swing.JButton();
        label_homescreen_currentUsername = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        token_validator_panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combo_homescreen_station = new javax.swing.JComboBox();
        button_homescreen_validate = new javax.swing.JButton();
        label_homescreen_tokenStatus = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        combo_homescreen_ticketIDList = new javax.swing.JComboBox();
        combo_homescreen_tokenIDList = new javax.swing.JComboBox();
        actions_panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        button_homescreen_checkIn = new javax.swing.JButton();
        button_homescreen_checkOut = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        label_fixed_cashierID = new javax.swing.JLabel();
        label_homescreen_driverID = new javax.swing.JLabel();
        checkout_panel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        combo_checkout_station = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        text_checkout_distance = new javax.swing.JTextField();
        button_checkout_checkoutConfirm = new javax.swing.JButton();
        button_checkout_cancel = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        profile_panel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        label_profile_userName = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        label_profile_userGender = new javax.swing.JLabel();
        panel_tokenQRCode1 = new javax.swing.JPanel();
        button_profile_edit = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        label_profile_userContactNumber = new javax.swing.JLabel();
        label_profile_userEmail = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        label_profile_userAddress = new javax.swing.JLabel();
        button_profile_back = new javax.swing.JButton();
        profile_edit_panel = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        panel_tokenQRCode2 = new javax.swing.JPanel();
        button_profiel_edit_done = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        button_profile_edit_cancel = new javax.swing.JButton();
        text_profile_edit_userName = new javax.swing.JTextField();
        text_profile_edit_userContactNumber = new javax.swing.JTextField();
        text_profile_edit_userEmail = new javax.swing.JTextField();
        combo_profile_edit_userGender = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea_profile_edit_userAddress = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PTTS v1.0  Driver Terminal");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homescreen_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_homescreen_logout.setText("Logout");
        button_homescreen_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_homescreen_logoutActionPerformed(evt);
            }
        });
        homescreen_panel.add(button_homescreen_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 14, -1, -1));

        button_homescreen_profile.setText("Profile");
        button_homescreen_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_homescreen_profileActionPerformed(evt);
            }
        });
        homescreen_panel.add(button_homescreen_profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 14, -1, -1));

        label_homescreen_currentUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_homescreen_currentUsername.setText("Username");
        homescreen_panel.add(label_homescreen_currentUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 11, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setText("Hi,");
        homescreen_panel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("System Date");
        homescreen_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("System Time");
        homescreen_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 87, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("#Date");
        homescreen_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 64, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("#Time");
        homescreen_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 87, -1, -1));

        token_validator_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Token Validator", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        token_validator_panel.setMaximumSize(new java.awt.Dimension(169, 208));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("TokenID");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Station");

        combo_homescreen_station.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gampaha", "Ragama", "Fort", "Panadura" }));

        button_homescreen_validate.setText("Validate");
        button_homescreen_validate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_homescreen_validateActionPerformed(evt);
            }
        });

        label_homescreen_tokenStatus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_homescreen_tokenStatus.setForeground(new java.awt.Color(0, 204, 51));
        label_homescreen_tokenStatus.setText("Status");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel29.setText("Ticket ID");

        combo_homescreen_ticketIDList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Empty List" }));
        combo_homescreen_ticketIDList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_homescreen_ticketIDListActionPerformed(evt);
            }
        });

        combo_homescreen_tokenIDList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Empty List" }));
        combo_homescreen_tokenIDList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_homescreen_tokenIDListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout token_validator_panelLayout = new javax.swing.GroupLayout(token_validator_panel);
        token_validator_panel.setLayout(token_validator_panelLayout);
        token_validator_panelLayout.setHorizontalGroup(
            token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(token_validator_panelLayout.createSequentialGroup()
                .addGroup(token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, token_validator_panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(button_homescreen_validate))
                    .addGroup(token_validator_panelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(token_validator_panelLayout.createSequentialGroup()
                                .addGroup(token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(15, 15, 15)
                                .addGroup(token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combo_homescreen_tokenIDList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combo_homescreen_station, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(token_validator_panelLayout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(11, 11, 11)
                                .addComponent(combo_homescreen_ticketIDList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(token_validator_panelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(label_homescreen_tokenStatus)))
                .addContainerGap())
        );
        token_validator_panelLayout.setVerticalGroup(
            token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(token_validator_panelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(combo_homescreen_station, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(combo_homescreen_tokenIDList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(combo_homescreen_ticketIDList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(button_homescreen_validate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_homescreen_tokenStatus)
                .addContainerGap())
        );

        homescreen_panel.add(token_validator_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        actions_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actions", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Class");
        jLabel7.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Type");
        jLabel8.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("To");
        jLabel9.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("From");
        jLabel10.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Start Date");
        jLabel11.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Ticket Summery");
        jLabel12.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("#reportID");
        jLabel14.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("#inspectorID");
        jLabel15.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("#station");
        jLabel16.setEnabled(false);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("#passengerID");
        jLabel17.setEnabled(false);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("#tokenID");
        jLabel18.setEnabled(false);

        button_homescreen_checkIn.setText("Check-In");
        button_homescreen_checkIn.setEnabled(false);
        button_homescreen_checkIn.setMargin(new java.awt.Insets(2, 3, 2, 3));
        button_homescreen_checkIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_homescreen_checkInActionPerformed(evt);
            }
        });

        button_homescreen_checkOut.setText("Check-Out");
        button_homescreen_checkOut.setEnabled(false);
        button_homescreen_checkOut.setMargin(new java.awt.Insets(2, 3, 2, 3));
        button_homescreen_checkOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_homescreen_checkOutActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("End Date");
        jLabel13.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("#tokenID");
        jLabel19.setEnabled(false);

        javax.swing.GroupLayout actions_panelLayout = new javax.swing.GroupLayout(actions_panel);
        actions_panel.setLayout(actions_panelLayout);
        actions_panelLayout.setHorizontalGroup(
            actions_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actions_panelLayout.createSequentialGroup()
                .addGroup(actions_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(actions_panelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel12))
                    .addGroup(actions_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(actions_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13))
                        .addGap(20, 20, 20)
                        .addGroup(actions_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(actions_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_homescreen_checkOut, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(button_homescreen_checkIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        actions_panelLayout.setVerticalGroup(
            actions_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actions_panelLayout.createSequentialGroup()
                .addGroup(actions_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(actions_panelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(actions_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(actions_panelLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18))
                            .addGroup(actions_panelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(actions_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel19)))
                    .addGroup(actions_panelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(button_homescreen_checkIn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(button_homescreen_checkOut, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        homescreen_panel.add(actions_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 64, -1, -1));

        label_fixed_cashierID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_fixed_cashierID.setText("Driver ID:");
        homescreen_panel.add(label_fixed_cashierID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 38, -1, -1));

        label_homescreen_driverID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_homescreen_driverID.setText("#driverID");
        homescreen_panel.add(label_homescreen_driverID, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 38, -1, -1));

        checkout_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Checkout Panel", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Station");

        combo_checkout_station.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gampaha", "Ragama", "Fort", "Panadura" }));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Distance");

        text_checkout_distance.setText("#distance");

        button_checkout_checkoutConfirm.setText("<html><center>Check-Out<br>Confirm</center>");
        button_checkout_checkoutConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_checkout_checkoutConfirmActionPerformed(evt);
            }
        });

        button_checkout_cancel.setText("Back");
        button_checkout_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_checkout_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout checkout_panelLayout = new javax.swing.GroupLayout(checkout_panel);
        checkout_panel.setLayout(checkout_panelLayout);
        checkout_panelLayout.setHorizontalGroup(
            checkout_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkout_panelLayout.createSequentialGroup()
                .addGroup(checkout_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(checkout_panelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_checkout_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(checkout_panelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(checkout_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(checkout_panelLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(combo_checkout_station, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(button_checkout_checkoutConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(checkout_panelLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(text_checkout_distance, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        checkout_panelLayout.setVerticalGroup(
            checkout_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkout_panelLayout.createSequentialGroup()
                .addGroup(checkout_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkout_panelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(checkout_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(combo_checkout_station, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(checkout_panelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(button_checkout_checkoutConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(checkout_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(text_checkout_distance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(button_checkout_cancel)
                .addContainerGap())
        );

        homescreen_panel.add(checkout_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 64, 310, 250));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("Simulation");
        homescreen_panel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 45, -1, -1));

        jCheckBox1.setText("Set validation result to false");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        homescreen_panel.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        getContentPane().add(homescreen_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, -1));

        profile_panel.setEnabled(false);
        profile_panel.setPreferredSize(new java.awt.Dimension(543, 343));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Profile");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Name");

        label_profile_userName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_profile_userName.setText("userName");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Gender");

        label_profile_userGender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_profile_userGender.setText("userGender");

        panel_tokenQRCode1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_tokenQRCode1.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout panel_tokenQRCode1Layout = new javax.swing.GroupLayout(panel_tokenQRCode1);
        panel_tokenQRCode1.setLayout(panel_tokenQRCode1Layout);
        panel_tokenQRCode1Layout.setHorizontalGroup(
            panel_tokenQRCode1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );
        panel_tokenQRCode1Layout.setVerticalGroup(
            panel_tokenQRCode1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );

        button_profile_edit.setText("Edit");
        button_profile_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_profile_editActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Contact Number");

        label_profile_userContactNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_profile_userContactNumber.setText("userContactNumber");

        label_profile_userEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_profile_userEmail.setText("userEmail");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Email");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("Address");

        label_profile_userAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_profile_userAddress.setText("userAddress");

        button_profile_back.setText("Back");
        button_profile_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_profile_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profile_panelLayout = new javax.swing.GroupLayout(profile_panel);
        profile_panel.setLayout(profile_panelLayout);
        profile_panelLayout.setHorizontalGroup(
            profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profile_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profile_panelLayout.createSequentialGroup()
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel27)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))
                        .addGap(18, 18, 18)
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profile_panelLayout.createSequentialGroup()
                                .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_profile_userName)
                                    .addComponent(label_profile_userGender)
                                    .addComponent(label_profile_userContactNumber)
                                    .addComponent(label_profile_userEmail))
                                .addGap(0, 293, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profile_panelLayout.createSequentialGroup()
                                .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(profile_panelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(button_profile_edit))
                                    .addGroup(profile_panelLayout.createSequentialGroup()
                                        .addComponent(label_profile_userAddress)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(button_profile_back)))
                                .addGap(26, 26, 26))))
                    .addGroup(profile_panelLayout.createSequentialGroup()
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(panel_tokenQRCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        profile_panelLayout.setVerticalGroup(
            profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profile_panelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(button_profile_edit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_tokenQRCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(profile_panelLayout.createSequentialGroup()
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(label_profile_userName))
                        .addGap(18, 18, 18)
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(label_profile_userGender))
                        .addGap(18, 18, 18)
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(label_profile_userContactNumber))
                        .addGap(18, 18, 18)
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(label_profile_userEmail))
                        .addGap(18, 18, 18)
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_profile_userAddress)
                            .addComponent(jLabel31)))
                    .addComponent(button_profile_back))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(profile_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 320));

        profile_edit_panel.setEnabled(false);
        profile_edit_panel.setPreferredSize(new java.awt.Dimension(500, 370));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Profile");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Name");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Gender");

        panel_tokenQRCode2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_tokenQRCode2.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout panel_tokenQRCode2Layout = new javax.swing.GroupLayout(panel_tokenQRCode2);
        panel_tokenQRCode2.setLayout(panel_tokenQRCode2Layout);
        panel_tokenQRCode2Layout.setHorizontalGroup(
            panel_tokenQRCode2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );
        panel_tokenQRCode2Layout.setVerticalGroup(
            panel_tokenQRCode2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );

        button_profiel_edit_done.setText("Done");
        button_profiel_edit_done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_profiel_edit_doneActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setText("Contact Number");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel36.setText("Email");

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel37.setText("Address");

        jButton12.setText("Change Picture");

        button_profile_edit_cancel.setText("Cancel");
        button_profile_edit_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_profile_edit_cancelActionPerformed(evt);
            }
        });

        text_profile_edit_userName.setText("userName");

        text_profile_edit_userContactNumber.setText("userContactNumber");

        text_profile_edit_userEmail.setText("userEmail");

        combo_profile_edit_userGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(173, 54));

        textArea_profile_edit_userAddress.setColumns(20);
        textArea_profile_edit_userAddress.setLineWrap(true);
        textArea_profile_edit_userAddress.setRows(5);
        textArea_profile_edit_userAddress.setText("userAddress");
        textArea_profile_edit_userAddress.setPreferredSize(new java.awt.Dimension(173, 54));
        jScrollPane2.setViewportView(textArea_profile_edit_userAddress);

        javax.swing.GroupLayout profile_edit_panelLayout = new javax.swing.GroupLayout(profile_edit_panel);
        profile_edit_panel.setLayout(profile_edit_panelLayout);
        profile_edit_panelLayout.setHorizontalGroup(
            profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profile_edit_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profile_edit_panelLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_profiel_edit_done))
                    .addGroup(profile_edit_panelLayout.createSequentialGroup()
                        .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel28)
                            .addComponent(jLabel33)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37))
                        .addGap(18, 18, 18)
                        .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profile_edit_panelLayout.createSequentialGroup()
                                .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(text_profile_edit_userName)
                                    .addComponent(text_profile_edit_userContactNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(text_profile_edit_userEmail)
                                    .addComponent(combo_profile_edit_userGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(profile_edit_panelLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                                .addComponent(button_profile_edit_cancel))))
                    .addGroup(profile_edit_panelLayout.createSequentialGroup()
                        .addComponent(panel_tokenQRCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12)))
                .addContainerGap())
        );
        profile_edit_panelLayout.setVerticalGroup(
            profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profile_edit_panelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(button_profiel_edit_done))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton12)
                    .addComponent(panel_tokenQRCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profile_edit_panelLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel33)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel36)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel37)
                        .addGap(60, 60, 60))
                    .addGroup(profile_edit_panelLayout.createSequentialGroup()
                        .addComponent(text_profile_edit_userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combo_profile_edit_userGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text_profile_edit_userContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text_profile_edit_userEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_profile_edit_cancel))
                        .addContainerGap())))
        );

        getContentPane().add(profile_edit_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_homescreen_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_homescreen_profileActionPerformed
        // TODO add your handling code here:
        hide_panels();
        profile_panel.setVisible(true);
    }//GEN-LAST:event_button_homescreen_profileActionPerformed

    private void button_profile_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_profile_editActionPerformed
        // TODO add your handling code here:
        profile_panel.setVisible(false);
        profile_edit_panel.setVisible(true);
    }//GEN-LAST:event_button_profile_editActionPerformed

    private void button_profile_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_profile_backActionPerformed
        // TODO add your handling code here:
        profile_panel.setVisible(false);
        homescreen_panel.setVisible(true);
    }//GEN-LAST:event_button_profile_backActionPerformed

    private void button_profiel_edit_doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_profiel_edit_doneActionPerformed
        // TODO add your handling code here:
//        int userType = currentInspector.getUserType();
//        String userID = currentInspector.getUserID();
//        String userPassword = currentInspector.getUserPassword();
//        String username = text_profile_edit_userName.getText();
//        int gender = combo_profile_edit_userGender.getSelectedIndex();
//        String contactNumber = text_profile_edit_userContactNumber.getText();
//        String email = text_profile_edit_userEmail.getText();
//        String address = textArea_profile_edit_userAddress.getText();
//
//        Inspector tempAdmin =  new Inspector(userID, userType, userPassword,currentInspector.isActive(), username, gender,contactNumber, email, address );

        //        if(PublicTransportTicketingSystem.adminController.updateUser(tempAdmin, userType, userID)){
            //            JOptionPane.showMessageDialog(null, "Inspector("+ userID +") has been successfully updated");
            //            //currentInspector = tempAdmin;
            //            currentInspector = PublicTransportTicketingSystem.adminController.getCurrentAdmin();
            //            populate_home_screen_panel();
            //            profile_edit_panel.setVisible(false);
            //            profile_panel.setVisible(true);
            //            populate_profile_and_edit_panels();
            //        }
        //        else{
            //            JOptionPane.showMessageDialog(this, "Inspector("+ userID +") NOT updated!","Inane error",JOptionPane.ERROR_MESSAGE);
            //        }
    }//GEN-LAST:event_button_profiel_edit_doneActionPerformed

    private void button_profile_edit_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_profile_edit_cancelActionPerformed
        // TODO add your handling code here:
        profile_edit_panel.setVisible(false);
        profile_panel.setVisible(true);
    }//GEN-LAST:event_button_profile_edit_cancelActionPerformed

    private void button_homescreen_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_homescreen_logoutActionPerformed
        // TODO add your handling code here:
        new LogoutConfirm(5).setVisible(true);
    }//GEN-LAST:event_button_homescreen_logoutActionPerformed

    private void button_homescreen_validateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_homescreen_validateActionPerformed
        // TODO add your handling code here:
        currentStation  = combo_homescreen_station.getSelectedItem().toString();
        String tokenID = combo_homescreen_tokenIDList.getSelectedItem().toString();
        String ticketID= combo_homescreen_ticketIDList.getSelectedItem().toString();
        try {
            currentToken = TokenManager.getTokenByID(tokenID);
            currentTicket = TicketManager.getTicketByID(ticketID);
            
            if(TokenValidator.validate(currentToken,currentStation)){
                label_homescreen_tokenStatus.setText("Valid");
                label_homescreen_tokenStatus.setForeground(Color.GREEN);
                label_homescreen_tokenStatus.setVisible(true);
                button_homescreen_checkIn.setEnabled(true);

            }
            else{
                label_homescreen_tokenStatus.setText("Invalid");
                label_homescreen_tokenStatus.setForeground(Color.RED);
                label_homescreen_tokenStatus.setVisible(true);

            }
        } catch (Exception e) {
            
            e.printStackTrace();
        }
    }//GEN-LAST:event_button_homescreen_validateActionPerformed

    private void button_homescreen_checkInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_homescreen_checkInActionPerformed
        // TODO add your handling code here:
        CheckIn checkIn = new CheckIn(currentStation,Calendar.getInstance(),1);
        currentTicket.addCheckIn(checkIn);
        JOptionPane.showMessageDialog(null, "Checked in successfully", "Message", JOptionPane.INFORMATION_MESSAGE);
        button_homescreen_checkIn.setEnabled(false);
        button_homescreen_checkOut.setEnabled(true);
    }//GEN-LAST:event_button_homescreen_checkInActionPerformed

    private void button_homescreen_checkOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_homescreen_checkOutActionPerformed
        // TODO add your handling code here:
        actions_panel.setVisible(false);
        checkout_panel.setVisible(true);
    }//GEN-LAST:event_button_homescreen_checkOutActionPerformed

    private void combo_homescreen_tokenIDListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_homescreen_tokenIDListActionPerformed
        // TODO add your handling code here:
        currentToken = TokenManager.getTokenByID(combo_homescreen_tokenIDList.getSelectedItem().toString());
        if(currentToken != null){
            loadActiveTicketList();
        }
    }//GEN-LAST:event_combo_homescreen_tokenIDListActionPerformed

    private void combo_homescreen_ticketIDListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_homescreen_ticketIDListActionPerformed
        // TODO add your handling code here:
        currentTicket = TicketManager.getTicketByID(combo_homescreen_ticketIDList.getSelectedItem().toString());
        
        //debugging
        System.out.println("Selected tikcet: "+combo_homescreen_ticketIDList.getSelectedItem().toString());
        Ticket currentTicket2 = TicketManager.getTicketByID("2016T1");
        System.out.println("c2: "+currentTicket2.getTicketID());
        //debugging
        
        if(currentTicket != null){
            button_homescreen_validate.setEnabled(true);   
        }
        else{
            JOptionPane.showMessageDialog(null,"Selected tikcet cannot be used! Contact Admin", "Message", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_combo_homescreen_ticketIDListActionPerformed

    private void button_checkout_checkoutConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_checkout_checkoutConfirmActionPerformed
        // TODO add your handling code here:
        String station= combo_checkout_station.getSelectedItem().toString();
        float distanceIncrement = Float.valueOf(text_checkout_distance.getText());
        
        CheckIn newCheckOut = new CheckIn(station, Calendar.getInstance(), 0);
        currentTicket.addCheckIn(newCheckOut);
        currentTicket.addDistance(distanceIncrement);
        System.out.println("Driver Temrinal: Check out added to the current[temp] ticket "+currentTicket.getTicketID());
        currentToken.removeTicketByID(currentTicket.getTicketID());
        currentToken.addTicket(currentTicket);
        
        //updating the ticket manager, token manager and passenger managers
        if(driverController.ticketCheckOutUpdates(currentTicket, currentToken, distanceIncrement)){
            JOptionPane.showMessageDialog(null,"Check out added to Ticket "+currentTicket.getTicketID()+" successfully", "Message", JOptionPane.INFORMATION_MESSAGE);
            combo_checkout_station.setEnabled(false);
            text_checkout_distance.setEnabled(false);
            button_checkout_checkoutConfirm.setEnabled(false);
            loadTokenList();
            String[] ticketIDList = {"Empty List"};
            combo_homescreen_ticketIDList.setModel(new DefaultComboBoxModel(ticketIDList));
            button_homescreen_validate.setEnabled(false);
            label_homescreen_tokenStatus.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null,"Check out NOT added to Ticket "+currentTicket.getTicketID()+" !", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_button_checkout_checkoutConfirmActionPerformed

    private void button_checkout_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_checkout_cancelActionPerformed
        // TODO add your handling code here:
        checkout_panel.setVisible(false);
        actions_panel.setVisible(true);
        button_checkout_checkoutConfirm.setEnabled(true);
        loadTokenList();
        
        String[] tokenIDList = {"Empty List"};
        combo_homescreen_ticketIDList.setModel(new DefaultComboBoxModel(tokenIDList));
        button_homescreen_validate.setEnabled(false);
        
        button_homescreen_checkOut.setEnabled(false);
        
        
    }//GEN-LAST:event_button_checkout_cancelActionPerformed

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        // TODO add your handling code here:
        boolean state = !jCheckBox1.isSelected();
        TokenValidator.status = state;
    }//GEN-LAST:event_jCheckBox1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DriverTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DriverTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DriverTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DriverTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new DriverTerminal().setVisible(true);
                driverTerminal.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actions_panel;
    private javax.swing.JButton button_checkout_cancel;
    private javax.swing.JButton button_checkout_checkoutConfirm;
    private javax.swing.JButton button_homescreen_checkIn;
    private javax.swing.JButton button_homescreen_checkOut;
    private javax.swing.JButton button_homescreen_logout;
    private javax.swing.JButton button_homescreen_profile;
    private javax.swing.JButton button_homescreen_validate;
    private javax.swing.JButton button_profiel_edit_done;
    private javax.swing.JButton button_profile_back;
    private javax.swing.JButton button_profile_edit;
    private javax.swing.JButton button_profile_edit_cancel;
    private javax.swing.JPanel checkout_panel;
    private javax.swing.JComboBox combo_checkout_station;
    private javax.swing.JComboBox combo_homescreen_station;
    private javax.swing.JComboBox combo_homescreen_ticketIDList;
    private javax.swing.JComboBox combo_homescreen_tokenIDList;
    private javax.swing.JComboBox combo_profile_edit_userGender;
    private javax.swing.JPanel homescreen_panel;
    private javax.swing.JButton jButton12;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_fixed_cashierID;
    private javax.swing.JLabel label_homescreen_currentUsername;
    private javax.swing.JLabel label_homescreen_driverID;
    private javax.swing.JLabel label_homescreen_tokenStatus;
    private javax.swing.JLabel label_profile_userAddress;
    private javax.swing.JLabel label_profile_userContactNumber;
    private javax.swing.JLabel label_profile_userEmail;
    private javax.swing.JLabel label_profile_userGender;
    private javax.swing.JLabel label_profile_userName;
    private javax.swing.JPanel panel_tokenQRCode1;
    private javax.swing.JPanel panel_tokenQRCode2;
    private javax.swing.JPanel profile_edit_panel;
    private javax.swing.JPanel profile_panel;
    private javax.swing.JTextArea textArea_profile_edit_userAddress;
    private javax.swing.JTextField text_checkout_distance;
    private javax.swing.JTextField text_profile_edit_userContactNumber;
    private javax.swing.JTextField text_profile_edit_userEmail;
    private javax.swing.JTextField text_profile_edit_userName;
    private javax.swing.JPanel token_validator_panel;
    // End of variables declaration//GEN-END:variables
}
