
package ptts.gui.gateoperator;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ptts.entities.GateOperator;
import ptts.entities.Token;
import ptts.entities.managers.TokenManager;
import ptts.gui.LogoutConfirm;
import static ptts.main.PublicTransportTicketingSystem.gateOperatorController;
import ptts.services.TokenValidator;

/**
 *
 * @author Siri@MnS
 */
public class GateOperatorTerminal extends javax.swing.JFrame {

    /**
     * Creates new form GateControllerTerminal
     */
    //public static JFrame gateOperatorTerminal = new GateOperatorTerminal();
    public static JFrame gateOperatorTerminal;
    private GateOperator currentGateOperator;
    
    public GateOperatorTerminal() {
        initComponents();
        setLocationRelativeTo(null); //centering the JFrame in the computer display
        hide_panels();
        
        currentGateOperator = gateOperatorController.getCurrentGateOperator();
        
        populate_homescreen_panel();
        homescreen_panel.setVisible(true);
    }

    private void hide_panels(){
        homescreen_panel.setVisible(false);
        profile_edit_panel.setVisible(false);
        profile_panel.setVisible(false);
    }
    
    private void populate_homescreen_panel(){
        label_homescreen_currentUsername.setText(currentGateOperator.getName());
        label_homescreen_gateOperatorID.setText(currentGateOperator.getUserID());
        loadTokenList();
        label_homescreen_tokenStatus.setVisible(false);
        jCheckBox1.setSelected(!TokenValidator.status);
    }
    
    private void populate_profile_and_edit_panels(){
    }
    
    private void loadTokenList(){
        ArrayList<Token> tempTokenList = TokenManager.getTokenList();

        if (tempTokenList != null) {
            String[] tokenIDList = new String[tempTokenList.size()];
            for (int i = 0; i < tempTokenList.size(); i++) {
                tokenIDList[i] = tempTokenList.get(i).getTokenID();
            }
            
            combo_homescreen_tokenIDList.setModel(new DefaultComboBoxModel(tokenIDList));
            button_homescreen_validate.setEnabled(true);
            
        }
        else{
            String[] tokenIDList = {"Empty List"};
            combo_homescreen_tokenIDList.setModel(new DefaultComboBoxModel(tokenIDList));
            button_homescreen_validate.setEnabled(false);
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homescreen_panel = new javax.swing.JPanel();
        button_homescreen_logout = new javax.swing.JButton();
        button_homescreen_profile = new javax.swing.JButton();
        label_homescreen_currentUsername = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        token_validator_panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combo_homescreen_station = new javax.swing.JComboBox();
        button_homescreen_validate = new javax.swing.JButton();
        label_homescreen_tokenStatus = new javax.swing.JLabel();
        combo_homescreen_tokenIDList = new javax.swing.JComboBox();
        case_report_panel = new javax.swing.JPanel();
        button_homescreen_closeGate = new javax.swing.JButton();
        button_homescreen_openGate = new javax.swing.JButton();
        label_fixed_cashierID = new javax.swing.JLabel();
        label_homescreen_gateOperatorID = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel32 = new javax.swing.JLabel();
        profile_panel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        label_profile_userName = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        label_profile_userGender = new javax.swing.JLabel();
        panel_tokenQRCode1 = new javax.swing.JPanel();
        button_profile_edit = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        label_profile_userContactNumber = new javax.swing.JLabel();
        label_profile_userEmail = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        label_profile_userAddress = new javax.swing.JLabel();
        button_profile_back = new javax.swing.JButton();
        profile_edit_panel = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        panel_tokenQRCode2 = new javax.swing.JPanel();
        button_profiel_edit_done = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        button_profile_edit_cancel = new javax.swing.JButton();
        text_profile_edit_userName = new javax.swing.JTextField();
        text_profile_edit_userContactNumber = new javax.swing.JTextField();
        text_profile_edit_userEmail = new javax.swing.JTextField();
        combo_profile_edit_userGender = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea_profile_edit_userAddress = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PTTS v1.0  Gate Operator Terminal");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_homescreen_logout.setText("Logout");
        button_homescreen_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_homescreen_logoutActionPerformed(evt);
            }
        });

        button_homescreen_profile.setText("Profile");
        button_homescreen_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_homescreen_profileActionPerformed(evt);
            }
        });

        label_homescreen_currentUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_homescreen_currentUsername.setText("Username");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setText("Hi,");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("System Date");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("System Time");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("#Date");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("#Time");

        token_validator_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Token Validator", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("TokenID");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Station");

        combo_homescreen_station.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gampaha", "Ragama", "Fort", "Panadura" }));

        button_homescreen_validate.setText("Validate");
        button_homescreen_validate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_homescreen_validateActionPerformed(evt);
            }
        });

        label_homescreen_tokenStatus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_homescreen_tokenStatus.setForeground(new java.awt.Color(0, 204, 51));
        label_homescreen_tokenStatus.setText("Status");

        combo_homescreen_tokenIDList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gampaha", "Ragama", "Fort", "Panadura" }));

        javax.swing.GroupLayout token_validator_panelLayout = new javax.swing.GroupLayout(token_validator_panel);
        token_validator_panel.setLayout(token_validator_panelLayout);
        token_validator_panelLayout.setHorizontalGroup(
            token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(token_validator_panelLayout.createSequentialGroup()
                .addGroup(token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(token_validator_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_homescreen_validate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(token_validator_panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combo_homescreen_tokenIDList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(token_validator_panelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(combo_homescreen_station, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(token_validator_panelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(label_homescreen_tokenStatus)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        token_validator_panelLayout.setVerticalGroup(
            token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(token_validator_panelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(combo_homescreen_station, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(combo_homescreen_tokenIDList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_homescreen_validate)
                .addGap(18, 18, 18)
                .addComponent(label_homescreen_tokenStatus)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        case_report_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actions", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        button_homescreen_closeGate.setText("Close Gate");
        button_homescreen_closeGate.setEnabled(false);
        button_homescreen_closeGate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_homescreen_closeGateActionPerformed(evt);
            }
        });

        button_homescreen_openGate.setText("Open Gate");
        button_homescreen_openGate.setEnabled(false);
        button_homescreen_openGate.setMargin(new java.awt.Insets(2, 3, 2, 3));
        button_homescreen_openGate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_homescreen_openGateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout case_report_panelLayout = new javax.swing.GroupLayout(case_report_panel);
        case_report_panel.setLayout(case_report_panelLayout);
        case_report_panelLayout.setHorizontalGroup(
            case_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(case_report_panelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(button_homescreen_openGate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_homescreen_closeGate, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        case_report_panelLayout.setVerticalGroup(
            case_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(case_report_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(case_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_homescreen_openGate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_homescreen_closeGate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        label_fixed_cashierID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_fixed_cashierID.setText("GateOperator ID:");

        label_homescreen_gateOperatorID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_homescreen_gateOperatorID.setText("#userID");

        jCheckBox1.setText("Set validation result to false");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("Simulation");

        javax.swing.GroupLayout homescreen_panelLayout = new javax.swing.GroupLayout(homescreen_panel);
        homescreen_panel.setLayout(homescreen_panelLayout);
        homescreen_panelLayout.setHorizontalGroup(
            homescreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homescreen_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homescreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homescreen_panelLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_homescreen_currentUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_homescreen_profile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_homescreen_logout)
                        .addGap(90, 90, 90))
                    .addGroup(homescreen_panelLayout.createSequentialGroup()
                        .addComponent(label_fixed_cashierID)
                        .addGap(18, 18, 18)
                        .addComponent(label_homescreen_gateOperatorID)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(homescreen_panelLayout.createSequentialGroup()
                        .addGroup(homescreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homescreen_panelLayout.createSequentialGroup()
                                .addGroup(homescreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(homescreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))
                            .addComponent(token_validator_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(homescreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homescreen_panelLayout.createSequentialGroup()
                                .addComponent(case_report_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homescreen_panelLayout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox1)
                                .addGap(99, 99, 99))))))
        );
        homescreen_panelLayout.setVerticalGroup(
            homescreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homescreen_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homescreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_homescreen_logout)
                    .addComponent(button_homescreen_profile)
                    .addComponent(label_homescreen_currentUsername)
                    .addComponent(jLabel34))
                .addGap(1, 1, 1)
                .addGroup(homescreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homescreen_panelLayout.createSequentialGroup()
                        .addGroup(homescreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_fixed_cashierID)
                            .addComponent(label_homescreen_gateOperatorID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(homescreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homescreen_panelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(homescreen_panelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(token_validator_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homescreen_panelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(homescreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox1)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(case_report_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(homescreen_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 320));

        profile_panel.setPreferredSize(new java.awt.Dimension(543, 323));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Profile");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Name");

        label_profile_userName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_profile_userName.setText("userName");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Gender");

        label_profile_userGender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_profile_userGender.setText("userGender");

        panel_tokenQRCode1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_tokenQRCode1.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout panel_tokenQRCode1Layout = new javax.swing.GroupLayout(panel_tokenQRCode1);
        panel_tokenQRCode1.setLayout(panel_tokenQRCode1Layout);
        panel_tokenQRCode1Layout.setHorizontalGroup(
            panel_tokenQRCode1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );
        panel_tokenQRCode1Layout.setVerticalGroup(
            panel_tokenQRCode1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );

        button_profile_edit.setText("Edit");
        button_profile_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_profile_editActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Contact Number");

        label_profile_userContactNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_profile_userContactNumber.setText("userContactNumber");

        label_profile_userEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_profile_userEmail.setText("userEmail");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Email");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("Address");

        label_profile_userAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_profile_userAddress.setText("userAddress");

        button_profile_back.setText("Back");
        button_profile_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_profile_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profile_panelLayout = new javax.swing.GroupLayout(profile_panel);
        profile_panel.setLayout(profile_panelLayout);
        profile_panelLayout.setHorizontalGroup(
            profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profile_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profile_panelLayout.createSequentialGroup()
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel27)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))
                        .addGap(18, 18, 18)
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profile_panelLayout.createSequentialGroup()
                                .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_profile_userName)
                                    .addComponent(label_profile_userGender)
                                    .addComponent(label_profile_userContactNumber)
                                    .addComponent(label_profile_userEmail))
                                .addGap(0, 293, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profile_panelLayout.createSequentialGroup()
                                .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(profile_panelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(button_profile_edit))
                                    .addGroup(profile_panelLayout.createSequentialGroup()
                                        .addComponent(label_profile_userAddress)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                                        .addComponent(button_profile_back)))
                                .addGap(26, 26, 26))))
                    .addGroup(profile_panelLayout.createSequentialGroup()
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(panel_tokenQRCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        profile_panelLayout.setVerticalGroup(
            profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profile_panelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(button_profile_edit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_tokenQRCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(profile_panelLayout.createSequentialGroup()
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(label_profile_userName))
                        .addGap(18, 18, 18)
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(label_profile_userGender))
                        .addGap(18, 18, 18)
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(label_profile_userContactNumber))
                        .addGap(18, 18, 18)
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(label_profile_userEmail))
                        .addGap(18, 18, 18)
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_profile_userAddress)
                            .addComponent(jLabel31)))
                    .addComponent(button_profile_back))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(profile_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        profile_edit_panel.setEnabled(false);
        profile_edit_panel.setPreferredSize(new java.awt.Dimension(543, 323));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Profile");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Name");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Gender");

        panel_tokenQRCode2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_tokenQRCode2.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout panel_tokenQRCode2Layout = new javax.swing.GroupLayout(panel_tokenQRCode2);
        panel_tokenQRCode2.setLayout(panel_tokenQRCode2Layout);
        panel_tokenQRCode2Layout.setHorizontalGroup(
            panel_tokenQRCode2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );
        panel_tokenQRCode2Layout.setVerticalGroup(
            panel_tokenQRCode2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );

        button_profiel_edit_done.setText("Done");
        button_profiel_edit_done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_profiel_edit_doneActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setText("Contact Number");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel36.setText("Email");

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel37.setText("Address");

        jButton12.setText("Change Picture");

        button_profile_edit_cancel.setText("Cancel");
        button_profile_edit_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_profile_edit_cancelActionPerformed(evt);
            }
        });

        text_profile_edit_userName.setText("userName");

        text_profile_edit_userContactNumber.setText("userContactNumber");

        text_profile_edit_userEmail.setText("userEmail");

        combo_profile_edit_userGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(173, 54));

        textArea_profile_edit_userAddress.setColumns(20);
        textArea_profile_edit_userAddress.setLineWrap(true);
        textArea_profile_edit_userAddress.setRows(5);
        textArea_profile_edit_userAddress.setText("userAddress");
        textArea_profile_edit_userAddress.setPreferredSize(new java.awt.Dimension(173, 54));
        jScrollPane2.setViewportView(textArea_profile_edit_userAddress);

        javax.swing.GroupLayout profile_edit_panelLayout = new javax.swing.GroupLayout(profile_edit_panel);
        profile_edit_panel.setLayout(profile_edit_panelLayout);
        profile_edit_panelLayout.setHorizontalGroup(
            profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profile_edit_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profile_edit_panelLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_profiel_edit_done))
                    .addGroup(profile_edit_panelLayout.createSequentialGroup()
                        .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel28)
                            .addComponent(jLabel33)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37))
                        .addGap(18, 18, 18)
                        .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profile_edit_panelLayout.createSequentialGroup()
                                .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(text_profile_edit_userName)
                                    .addComponent(text_profile_edit_userContactNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(text_profile_edit_userEmail)
                                    .addComponent(combo_profile_edit_userGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(profile_edit_panelLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                                .addComponent(button_profile_edit_cancel))))
                    .addGroup(profile_edit_panelLayout.createSequentialGroup()
                        .addComponent(panel_tokenQRCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12)))
                .addGap(26, 26, 26))
        );
        profile_edit_panelLayout.setVerticalGroup(
            profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profile_edit_panelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(button_profiel_edit_done))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton12)
                    .addComponent(panel_tokenQRCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profile_edit_panelLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel33)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel36)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel37)
                        .addGap(50, 50, 50))
                    .addGroup(profile_edit_panelLayout.createSequentialGroup()
                        .addComponent(text_profile_edit_userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combo_profile_edit_userGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text_profile_edit_userContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text_profile_edit_userEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_profile_edit_cancel)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(profile_edit_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_homescreen_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_homescreen_profileActionPerformed
        // TODO add your handling code here:
        hide_panels();
        profile_panel.setVisible(true);
    }//GEN-LAST:event_button_homescreen_profileActionPerformed

    private void button_profile_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_profile_editActionPerformed
        // TODO add your handling code here:
        hide_panels();
        profile_edit_panel.setVisible(true);
    }//GEN-LAST:event_button_profile_editActionPerformed

    private void button_profile_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_profile_backActionPerformed
        // TODO add your handling code here:
        hide_panels();
        homescreen_panel.setVisible(true);
    }//GEN-LAST:event_button_profile_backActionPerformed

    private void button_profiel_edit_doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_profiel_edit_doneActionPerformed
        // TODO add your handling code here:
        int userType = currentGateOperator.getUserType();
        String userID = currentGateOperator.getUserID();
        String userPassword = currentGateOperator.getUserPassword();
        String username = text_profile_edit_userName.getText();
        int gender = combo_profile_edit_userGender.getSelectedIndex();
        String contactNumber = text_profile_edit_userContactNumber.getText();
        String email = text_profile_edit_userEmail.getText();
        String address = textArea_profile_edit_userAddress.getText();

        GateOperator tempOperator =  new GateOperator(userID, userType, userPassword,currentGateOperator.isActive(), username, gender,contactNumber, email, address );

        //        if(PublicTransportTicketingSystem.adminController.updateUser(tempAdmin, userType, userID)){
            //            JOptionPane.showMessageDialog(null, "Inspector("+ userID +") has been successfully updated");
            //            //currentInspector = tempAdmin;
            //            currentInspector = PublicTransportTicketingSystem.adminController.getCurrentAdmin();
            //            populate_home_screen_panel();
            //            profile_edit_panel.setVisible(false);
            //            profile_panel.setVisible(true);
            //            populate_profile_and_edit_panels();
            //        }
        //        else{
            //            JOptionPane.showMessageDialog(this, "Inspector("+ userID +") NOT updated!","Inane error",JOptionPane.ERROR_MESSAGE);
            //        }
    }//GEN-LAST:event_button_profiel_edit_doneActionPerformed

    private void button_profile_edit_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_profile_edit_cancelActionPerformed
        // TODO add your handling code here:
        hide_panels();
        profile_panel.setVisible(true);
    }//GEN-LAST:event_button_profile_edit_cancelActionPerformed

    private void button_homescreen_closeGateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_homescreen_closeGateActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gate Closed", "Gate Operator", JOptionPane.INFORMATION_MESSAGE);
        button_homescreen_openGate.setEnabled(false);
        button_homescreen_closeGate.setEnabled(false);
        label_homescreen_tokenStatus.setVisible(false);
    }//GEN-LAST:event_button_homescreen_closeGateActionPerformed

    private void button_homescreen_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_homescreen_logoutActionPerformed
        // TODO add your handling code here:
        new LogoutConfirm(6).setVisible(true);
    }//GEN-LAST:event_button_homescreen_logoutActionPerformed

    private void button_homescreen_validateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_homescreen_validateActionPerformed
        // TODO add your handling code here:
        String station  = combo_homescreen_station.getSelectedItem().toString();
        String tokenID = combo_homescreen_tokenIDList.getSelectedItem().toString();
        try {
            Token currentToken = TokenManager.getTokenByID(tokenID);
            if(TokenValidator.validate(currentToken,station)){
                label_homescreen_tokenStatus.setText("Valid");
                label_homescreen_tokenStatus.setForeground(Color.GREEN);
                label_homescreen_tokenStatus.setVisible(true);
                button_homescreen_openGate.setEnabled(true);

            }
            else{
                label_homescreen_tokenStatus.setText("Invalid");
                label_homescreen_tokenStatus.setForeground(Color.RED);
                label_homescreen_tokenStatus.setVisible(true);

            }
        } catch (Exception e) {
            
            e.printStackTrace();
        }
    }//GEN-LAST:event_button_homescreen_validateActionPerformed

    private void button_homescreen_openGateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_homescreen_openGateActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gate Opened", "Gate Operator", JOptionPane.INFORMATION_MESSAGE);
        button_homescreen_openGate.setEnabled(false);
        button_homescreen_closeGate.setEnabled(true);
    }//GEN-LAST:event_button_homescreen_openGateActionPerformed

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        // TODO add your handling code here:
        boolean state = !jCheckBox1.isSelected();
        TokenValidator.status = state;
    }//GEN-LAST:event_jCheckBox1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GateOperatorTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GateOperatorTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GateOperatorTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GateOperatorTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GateOperatorTerminal().setVisible(true);
                gateOperatorTerminal.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_homescreen_closeGate;
    private javax.swing.JButton button_homescreen_logout;
    private javax.swing.JButton button_homescreen_openGate;
    private javax.swing.JButton button_homescreen_profile;
    private javax.swing.JButton button_homescreen_validate;
    private javax.swing.JButton button_profiel_edit_done;
    private javax.swing.JButton button_profile_back;
    private javax.swing.JButton button_profile_edit;
    private javax.swing.JButton button_profile_edit_cancel;
    private javax.swing.JPanel case_report_panel;
    private javax.swing.JComboBox combo_homescreen_station;
    private javax.swing.JComboBox combo_homescreen_tokenIDList;
    private javax.swing.JComboBox combo_profile_edit_userGender;
    private javax.swing.JPanel homescreen_panel;
    private javax.swing.JButton jButton12;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_fixed_cashierID;
    private javax.swing.JLabel label_homescreen_currentUsername;
    private javax.swing.JLabel label_homescreen_gateOperatorID;
    private javax.swing.JLabel label_homescreen_tokenStatus;
    private javax.swing.JLabel label_profile_userAddress;
    private javax.swing.JLabel label_profile_userContactNumber;
    private javax.swing.JLabel label_profile_userEmail;
    private javax.swing.JLabel label_profile_userGender;
    private javax.swing.JLabel label_profile_userName;
    private javax.swing.JPanel panel_tokenQRCode1;
    private javax.swing.JPanel panel_tokenQRCode2;
    private javax.swing.JPanel profile_edit_panel;
    private javax.swing.JPanel profile_panel;
    private javax.swing.JTextArea textArea_profile_edit_userAddress;
    private javax.swing.JTextField text_profile_edit_userContactNumber;
    private javax.swing.JTextField text_profile_edit_userEmail;
    private javax.swing.JTextField text_profile_edit_userName;
    private javax.swing.JPanel token_validator_panel;
    // End of variables declaration//GEN-END:variables
}
