
package ptts.gui.inspector;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ptts.entities.CaseReport;
import ptts.entities.Inspector;
import ptts.entities.Token;
import ptts.entities.managers.CaseReportManager;
import ptts.entities.managers.TokenManager;
import ptts.gui.LogoutConfirm;
import static ptts.main.PublicTransportTicketingSystem.inspectorController;
import ptts.services.TokenValidator;

/**
 *
 * @author Siri@MnS
 */
public class InspectorTerminal extends javax.swing.JFrame {

    /**
     * Creates new form InspectorTerminal
     */
    //public static JFrame inspectorTerminal = new InspectorTerminal();
    public static JFrame inspectorTerminal;
    private Inspector currentInspector;
    
    private Token currentToken;
    
    String station; 
    String tokenID;
    String reportID ;
    String inspectorID;
    String passengerID;
    Calendar calendar_date_time;
    String date;
    String time;
    
    public InspectorTerminal() {
        initComponents();
        setLocationRelativeTo(null); //centering the JFrame in the computer display
        hide_panels();

        currentInspector = inspectorController.getCurrentInspector();
        
        populate_home_screen_panel();
        populate_profile_and_edit_panels();
        homescreen_panel.setVisible(true);
        
    }

    private void populate_home_screen_panel(){
        label_homescreen_currentUsername.setText(currentInspector.getName());
        label_inspectorID.setText(currentInspector.getUserID());
        label_homescreen_tokenStatus.setVisible(false);
        jCheckBox1.setSelected(!TokenValidator.status);
        
        loadTokenList();
    }
    
    private void loadTokenList(){
        ArrayList<Token> tempTokenList = TokenManager.getTokenList();

        if (tempTokenList != null) {
            String[] tokenIDList = new String[tempTokenList.size()];
            for (int i = 0; i < tempTokenList.size(); i++) {
                tokenIDList[i] = tempTokenList.get(i).getTokenID();
            }
            
            combo_homescreen_tokenIDList.setModel(new DefaultComboBoxModel(tokenIDList));
            button_homescreen_validate.setEnabled(true);
        }
        else{
            String[] tokenIDList = {"Empty List"};
            combo_homescreen_tokenIDList.setModel(new DefaultComboBoxModel(tokenIDList));
            button_homescreen_validate.setEnabled(false);
        }
    }
    
    private void populate_profile_and_edit_panels(){
    }
    
    private void hide_panels(){
        homescreen_panel.setVisible(false);
        profile_panel.setVisible(false);
        profile_edit_panel.setVisible(false);
    }
    
    private void enable_case_report_panel(){
        label_homescreen_reportID.setEnabled(true);
        label_homescreen_inspectorID.setEnabled(true);
        label_homescreen_station.setEnabled(true);
        label_homescreen_passengerID.setEnabled(true);
        label_homescreen_tokenID.setEnabled(true);
        label_homescreen_date.setEnabled(true);
        label_homescreen_time.setEnabled(true);
        button_homescreen_sendReport.setEnabled(true);
        button_homescreen_cancel.setEnabled(true);        
        
    }
    
    private void disable_case_report_panel(){
        label_homescreen_reportID.setEnabled(false);
        label_homescreen_inspectorID.setEnabled(false);
        label_homescreen_station.setEnabled(false);
        label_homescreen_passengerID.setEnabled(false);
        label_homescreen_tokenID.setEnabled(false);
        label_homescreen_date.setEnabled(false);
        label_homescreen_time.setEnabled(false);
        button_homescreen_sendReport.setEnabled(false);
        button_homescreen_cancel.setEnabled(false);
    }
    
    private String  generateReportID(){
        int reportCount;
        
        try {
            reportCount = CaseReportManager.getCaseReportList().size();
        } catch (NullPointerException e) {
            reportCount =0;
            System.out.println("Inspector Terminal [generate reportID]: Null token list!");
        }
        
        StringBuilder sb = new StringBuilder("CR");
        sb.append(Integer.toString(reportCount+1));
        
        return sb.toString();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homescreen_panel = new javax.swing.JPanel();
        button_homescreen_logout = new javax.swing.JButton();
        button_homescreen_profile = new javax.swing.JButton();
        label_homescreen_currentUsername = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        token_validator_panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combo_homescreen_station = new javax.swing.JComboBox();
        button_homescreen_validate = new javax.swing.JButton();
        label_homescreen_tokenStatus = new javax.swing.JLabel();
        combo_homescreen_tokenIDList = new javax.swing.JComboBox();
        case_report_panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        label_homescreen_reportID = new javax.swing.JLabel();
        label_homescreen_inspectorID = new javax.swing.JLabel();
        label_homescreen_station = new javax.swing.JLabel();
        label_homescreen_passengerID = new javax.swing.JLabel();
        label_homescreen_tokenID = new javax.swing.JLabel();
        label_homescreen_date = new javax.swing.JLabel();
        label_homescreen_time = new javax.swing.JLabel();
        button_homescreen_cancel = new javax.swing.JButton();
        button_homescreen_sendReport = new javax.swing.JButton();
        label_fixed_cashierID = new javax.swing.JLabel();
        label_inspectorID = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        profile_panel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        label_profile_userName = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        label_profile_userGender = new javax.swing.JLabel();
        panel_tokenQRCode1 = new javax.swing.JPanel();
        button_profile_edit = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        label_profile_userContactNumber = new javax.swing.JLabel();
        label_profile_userEmail = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        label_profile_userAddress = new javax.swing.JLabel();
        button_profile_back = new javax.swing.JButton();
        profile_edit_panel = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        panel_tokenQRCode2 = new javax.swing.JPanel();
        button_profiel_edit_done = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        button_profile_edit_cancel = new javax.swing.JButton();
        text_profile_edit_userName = new javax.swing.JTextField();
        text_profile_edit_userContactNumber = new javax.swing.JTextField();
        text_profile_edit_userEmail = new javax.swing.JTextField();
        combo_profile_edit_userGender = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea_profile_edit_userAddress = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PTTS v1.0  Inspector Terminal");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_homescreen_logout.setText("Logout");
        button_homescreen_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_homescreen_logoutActionPerformed(evt);
            }
        });

        button_homescreen_profile.setText("Profile");
        button_homescreen_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_homescreen_profileActionPerformed(evt);
            }
        });

        label_homescreen_currentUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_homescreen_currentUsername.setText("Username");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setText("Hi,");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("System Date");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("System Time");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("#Date");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("#Time");

        token_validator_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Token Validator", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("TokenID");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Station");

        combo_homescreen_station.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gampaha", "Ragama", "Fort", "Panadura" }));

        button_homescreen_validate.setText("Validate");
        button_homescreen_validate.setEnabled(false);
        button_homescreen_validate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_homescreen_validateActionPerformed(evt);
            }
        });

        label_homescreen_tokenStatus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_homescreen_tokenStatus.setForeground(new java.awt.Color(0, 204, 51));
        label_homescreen_tokenStatus.setText("Status");

        combo_homescreen_tokenIDList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gampaha", "Ragama", "Fort", "Panadura" }));
        combo_homescreen_tokenIDList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo_homescreen_tokenIDListMouseClicked(evt);
            }
        });
        combo_homescreen_tokenIDList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_homescreen_tokenIDListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout token_validator_panelLayout = new javax.swing.GroupLayout(token_validator_panel);
        token_validator_panel.setLayout(token_validator_panelLayout);
        token_validator_panelLayout.setHorizontalGroup(
            token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(token_validator_panelLayout.createSequentialGroup()
                .addGroup(token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(token_validator_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, token_validator_panelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(button_homescreen_validate))
                            .addGroup(token_validator_panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(token_validator_panelLayout.createSequentialGroup()
                                        .addGap(0, 1, Short.MAX_VALUE)
                                        .addComponent(combo_homescreen_station, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(token_validator_panelLayout.createSequentialGroup()
                                        .addComponent(combo_homescreen_tokenIDList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(token_validator_panelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(label_homescreen_tokenStatus)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        token_validator_panelLayout.setVerticalGroup(
            token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(token_validator_panelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(combo_homescreen_station, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(token_validator_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(combo_homescreen_tokenIDList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_homescreen_validate)
                .addGap(18, 18, 18)
                .addComponent(label_homescreen_tokenStatus)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        case_report_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Case Report", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        case_report_panel.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Report ID");
        jLabel7.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Inspector ID");
        jLabel8.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Passenger ID");
        jLabel9.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Station");
        jLabel10.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Token ID");
        jLabel11.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Date");
        jLabel12.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Time");
        jLabel13.setEnabled(false);

        label_homescreen_reportID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_homescreen_reportID.setText("#reportID");
        label_homescreen_reportID.setEnabled(false);

        label_homescreen_inspectorID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_homescreen_inspectorID.setText("#inspectorID");
        label_homescreen_inspectorID.setEnabled(false);

        label_homescreen_station.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_homescreen_station.setText("#station");
        label_homescreen_station.setEnabled(false);

        label_homescreen_passengerID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_homescreen_passengerID.setText("#passengerID");
        label_homescreen_passengerID.setEnabled(false);

        label_homescreen_tokenID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_homescreen_tokenID.setText("#tokenID");
        label_homescreen_tokenID.setEnabled(false);

        label_homescreen_date.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_homescreen_date.setText("#Date");
        label_homescreen_date.setEnabled(false);

        label_homescreen_time.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_homescreen_time.setText("#Time");
        label_homescreen_time.setEnabled(false);

        button_homescreen_cancel.setText("Cancel");
        button_homescreen_cancel.setEnabled(false);
        button_homescreen_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_homescreen_cancelActionPerformed(evt);
            }
        });

        button_homescreen_sendReport.setText("Send Report");
        button_homescreen_sendReport.setEnabled(false);
        button_homescreen_sendReport.setMargin(new java.awt.Insets(2, 3, 2, 3));
        button_homescreen_sendReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_homescreen_sendReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout case_report_panelLayout = new javax.swing.GroupLayout(case_report_panel);
        case_report_panel.setLayout(case_report_panelLayout);
        case_report_panelLayout.setHorizontalGroup(
            case_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(case_report_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(case_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(case_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(case_report_panelLayout.createSequentialGroup()
                        .addGroup(case_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_homescreen_station)
                            .addComponent(label_homescreen_passengerID)
                            .addComponent(label_homescreen_tokenID))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(case_report_panelLayout.createSequentialGroup()
                        .addGroup(case_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_homescreen_reportID)
                            .addComponent(label_homescreen_inspectorID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(case_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(case_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_homescreen_date)
                            .addComponent(label_homescreen_time))
                        .addGap(37, 37, 37))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, case_report_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_homescreen_sendReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_homescreen_cancel)
                .addGap(12, 12, 12))
        );
        case_report_panelLayout.setVerticalGroup(
            case_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(case_report_panelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(case_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(case_report_panelLayout.createSequentialGroup()
                        .addGroup(case_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(case_report_panelLayout.createSequentialGroup()
                                .addComponent(label_homescreen_reportID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_homescreen_inspectorID))
                            .addGroup(case_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(case_report_panelLayout.createSequentialGroup()
                                    .addComponent(label_homescreen_date)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(label_homescreen_time))
                                .addGroup(case_report_panelLayout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel13))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_homescreen_station)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_homescreen_passengerID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_homescreen_tokenID))
                    .addGroup(case_report_panelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(case_report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_homescreen_sendReport)
                    .addComponent(button_homescreen_cancel))
                .addContainerGap())
        );

        label_fixed_cashierID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_fixed_cashierID.setText("Inspector ID:");

        label_inspectorID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_inspectorID.setText("#inspectorID");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Simulation");

        jCheckBox1.setText("Set validation result to false");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout homescreen_panelLayout = new javax.swing.GroupLayout(homescreen_panel);
        homescreen_panel.setLayout(homescreen_panelLayout);
        homescreen_panelLayout.setHorizontalGroup(
            homescreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homescreen_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homescreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homescreen_panelLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_homescreen_currentUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_homescreen_profile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_homescreen_logout)
                        .addGap(44, 44, 44))
                    .addGroup(homescreen_panelLayout.createSequentialGroup()
                        .addGroup(homescreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homescreen_panelLayout.createSequentialGroup()
                                .addGroup(homescreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(homescreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))
                            .addComponent(token_validator_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(case_report_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(homescreen_panelLayout.createSequentialGroup()
                        .addComponent(label_fixed_cashierID)
                        .addGap(18, 18, 18)
                        .addComponent(label_inspectorID)
                        .addGap(97, 97, 97)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        homescreen_panelLayout.setVerticalGroup(
            homescreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homescreen_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homescreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_homescreen_logout)
                    .addComponent(button_homescreen_profile)
                    .addComponent(label_homescreen_currentUsername)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homescreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homescreen_panelLayout.createSequentialGroup()
                        .addGroup(homescreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_fixed_cashierID)
                            .addComponent(label_inspectorID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(homescreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homescreen_panelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(homescreen_panelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(token_validator_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homescreen_panelLayout.createSequentialGroup()
                        .addGroup(homescreen_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(case_report_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(homescreen_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        profile_panel.setPreferredSize(new java.awt.Dimension(543, 323));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Profile");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Name");

        label_profile_userName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_profile_userName.setText("userName");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Gender");

        label_profile_userGender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_profile_userGender.setText("userGender");

        panel_tokenQRCode1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_tokenQRCode1.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout panel_tokenQRCode1Layout = new javax.swing.GroupLayout(panel_tokenQRCode1);
        panel_tokenQRCode1.setLayout(panel_tokenQRCode1Layout);
        panel_tokenQRCode1Layout.setHorizontalGroup(
            panel_tokenQRCode1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );
        panel_tokenQRCode1Layout.setVerticalGroup(
            panel_tokenQRCode1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );

        button_profile_edit.setText("Edit");
        button_profile_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_profile_editActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Contact Number");

        label_profile_userContactNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_profile_userContactNumber.setText("userContactNumber");

        label_profile_userEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_profile_userEmail.setText("userEmail");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Email");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("Address");

        label_profile_userAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_profile_userAddress.setText("userAddress");

        button_profile_back.setText("Back");
        button_profile_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_profile_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profile_panelLayout = new javax.swing.GroupLayout(profile_panel);
        profile_panel.setLayout(profile_panelLayout);
        profile_panelLayout.setHorizontalGroup(
            profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profile_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profile_panelLayout.createSequentialGroup()
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel27)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))
                        .addGap(18, 18, 18)
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profile_panelLayout.createSequentialGroup()
                                .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_profile_userName)
                                    .addComponent(label_profile_userGender)
                                    .addComponent(label_profile_userContactNumber)
                                    .addComponent(label_profile_userEmail))
                                .addGap(0, 293, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profile_panelLayout.createSequentialGroup()
                                .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(profile_panelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(button_profile_edit))
                                    .addGroup(profile_panelLayout.createSequentialGroup()
                                        .addComponent(label_profile_userAddress)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                                        .addComponent(button_profile_back)))
                                .addGap(26, 26, 26))))
                    .addGroup(profile_panelLayout.createSequentialGroup()
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(panel_tokenQRCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        profile_panelLayout.setVerticalGroup(
            profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profile_panelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(button_profile_edit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_tokenQRCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(profile_panelLayout.createSequentialGroup()
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(label_profile_userName))
                        .addGap(18, 18, 18)
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(label_profile_userGender))
                        .addGap(18, 18, 18)
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(label_profile_userContactNumber))
                        .addGap(18, 18, 18)
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(label_profile_userEmail))
                        .addGap(18, 18, 18)
                        .addGroup(profile_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_profile_userAddress)
                            .addComponent(jLabel31)))
                    .addComponent(button_profile_back))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(profile_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        profile_edit_panel.setEnabled(false);
        profile_edit_panel.setPreferredSize(new java.awt.Dimension(543, 323));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Profile");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Name");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Gender");

        panel_tokenQRCode2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_tokenQRCode2.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout panel_tokenQRCode2Layout = new javax.swing.GroupLayout(panel_tokenQRCode2);
        panel_tokenQRCode2.setLayout(panel_tokenQRCode2Layout);
        panel_tokenQRCode2Layout.setHorizontalGroup(
            panel_tokenQRCode2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );
        panel_tokenQRCode2Layout.setVerticalGroup(
            panel_tokenQRCode2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );

        button_profiel_edit_done.setText("Done");
        button_profiel_edit_done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_profiel_edit_doneActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setText("Contact Number");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel36.setText("Email");

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel37.setText("Address");

        jButton12.setText("Change Picture");

        button_profile_edit_cancel.setText("Cancel");
        button_profile_edit_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_profile_edit_cancelActionPerformed(evt);
            }
        });

        text_profile_edit_userName.setText("userName");

        text_profile_edit_userContactNumber.setText("userContactNumber");

        text_profile_edit_userEmail.setText("userEmail");

        combo_profile_edit_userGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(173, 54));

        textArea_profile_edit_userAddress.setColumns(20);
        textArea_profile_edit_userAddress.setLineWrap(true);
        textArea_profile_edit_userAddress.setRows(5);
        textArea_profile_edit_userAddress.setText("userAddress");
        textArea_profile_edit_userAddress.setPreferredSize(new java.awt.Dimension(173, 54));
        jScrollPane2.setViewportView(textArea_profile_edit_userAddress);

        javax.swing.GroupLayout profile_edit_panelLayout = new javax.swing.GroupLayout(profile_edit_panel);
        profile_edit_panel.setLayout(profile_edit_panelLayout);
        profile_edit_panelLayout.setHorizontalGroup(
            profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profile_edit_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profile_edit_panelLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_profiel_edit_done))
                    .addGroup(profile_edit_panelLayout.createSequentialGroup()
                        .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel28)
                            .addComponent(jLabel33)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37))
                        .addGap(18, 18, 18)
                        .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profile_edit_panelLayout.createSequentialGroup()
                                .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(text_profile_edit_userName)
                                    .addComponent(text_profile_edit_userContactNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(text_profile_edit_userEmail)
                                    .addComponent(combo_profile_edit_userGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(profile_edit_panelLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                                .addComponent(button_profile_edit_cancel))))
                    .addGroup(profile_edit_panelLayout.createSequentialGroup()
                        .addComponent(panel_tokenQRCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12)))
                .addGap(26, 26, 26))
        );
        profile_edit_panelLayout.setVerticalGroup(
            profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profile_edit_panelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(button_profiel_edit_done))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton12)
                    .addComponent(panel_tokenQRCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profile_edit_panelLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel33)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel36)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel37)
                        .addGap(50, 50, 50))
                    .addGroup(profile_edit_panelLayout.createSequentialGroup()
                        .addComponent(text_profile_edit_userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combo_profile_edit_userGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text_profile_edit_userContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text_profile_edit_userEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(profile_edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_profile_edit_cancel)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(profile_edit_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_profile_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_profile_editActionPerformed
        // TODO add your handling code here:
        profile_panel.setVisible(false);
        profile_edit_panel.setVisible(true);
    }//GEN-LAST:event_button_profile_editActionPerformed

    private void button_profile_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_profile_backActionPerformed
        // TODO add your handling code here:
        profile_panel.setVisible(false);
        homescreen_panel.setVisible(true);
    }//GEN-LAST:event_button_profile_backActionPerformed

    private void button_profiel_edit_doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_profiel_edit_doneActionPerformed
        // TODO add your handling code here:
        int userType = currentInspector.getUserType();
        String userID = currentInspector.getUserID();
        String userPassword = currentInspector.getUserPassword();
        String username = text_profile_edit_userName.getText();
        int gender = combo_profile_edit_userGender.getSelectedIndex();
        String contactNumber = text_profile_edit_userContactNumber.getText();
        String email = text_profile_edit_userEmail.getText();
        String address = textArea_profile_edit_userAddress.getText();

        Inspector tempAdmin =  new Inspector(userID, userType, userPassword,currentInspector.isActive(), username, gender,contactNumber, email, address );

//        if(PublicTransportTicketingSystem.adminController.updateUser(tempAdmin, userType, userID)){
//            JOptionPane.showMessageDialog(null, "Inspector("+ userID +") has been successfully updated");
//            //currentInspector = tempAdmin;
//            currentInspector = PublicTransportTicketingSystem.adminController.getCurrentAdmin();
//            populate_home_screen_panel();
//            profile_edit_panel.setVisible(false);
//            profile_panel.setVisible(true);
//            populate_profile_and_edit_panels();
//        }
//        else{
//            JOptionPane.showMessageDialog(this, "Inspector("+ userID +") NOT updated!","Inane error",JOptionPane.ERROR_MESSAGE);
//        }

    }//GEN-LAST:event_button_profiel_edit_doneActionPerformed

    private void button_profile_edit_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_profile_edit_cancelActionPerformed
        // TODO add your handling code here:
        profile_edit_panel.setVisible(false);
        profile_panel.setVisible(true);
    }//GEN-LAST:event_button_profile_edit_cancelActionPerformed

    private void button_homescreen_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_homescreen_profileActionPerformed
        // TODO add your handling code here:
        hide_panels();
        profile_panel.setVisible(true);
    }//GEN-LAST:event_button_homescreen_profileActionPerformed

    private void button_homescreen_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_homescreen_logoutActionPerformed
        // TODO add your handling code here:
        new LogoutConfirm(4).setVisible(true);
    }//GEN-LAST:event_button_homescreen_logoutActionPerformed

    private void button_homescreen_validateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_homescreen_validateActionPerformed
        // TODO add your handling code here:
        station  = combo_homescreen_station.getSelectedItem().toString();
        tokenID = combo_homescreen_tokenIDList.getSelectedItem().toString();
        try {
            currentToken = TokenManager.getTokenByID(tokenID);
            if(TokenValidator.validate(currentToken,station)){
                label_homescreen_tokenStatus.setText("Valid");
                label_homescreen_tokenStatus.setForeground(Color.GREEN);
                label_homescreen_tokenStatus.setVisible(true);
                disable_case_report_panel();
            }
            else{
                label_homescreen_tokenStatus.setText("Invalid");
                label_homescreen_tokenStatus.setForeground(Color.RED);
                label_homescreen_tokenStatus.setVisible(true);
                
                reportID = generateReportID();
                inspectorID = currentInspector.getUserID();
                passengerID = currentToken.getPassengerID();
                
                calendar_date_time = Calendar.getInstance();
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat timeFormat = new SimpleDateFormat("h:mm a");
                
                date = dateFormat.format(calendar_date_time.getTime());
                time = timeFormat.format(calendar_date_time.getTime());
                
                label_homescreen_reportID.setText(reportID);
                label_homescreen_inspectorID.setText(inspectorID);
                label_homescreen_station.setText(station);
                label_homescreen_passengerID.setText(passengerID);
                label_homescreen_tokenID.setText(tokenID);
                label_homescreen_date.setText(date);
                label_homescreen_time.setText(time);

                enable_case_report_panel();
            }
        } catch (Exception e) {
            
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_button_homescreen_validateActionPerformed

    private void button_homescreen_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_homescreen_cancelActionPerformed
        // TODO add your handling code here:
        disable_case_report_panel();
        label_homescreen_tokenStatus.setVisible(false);
        button_homescreen_validate.setEnabled(false);
    }//GEN-LAST:event_button_homescreen_cancelActionPerformed

    private void combo_homescreen_tokenIDListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo_homescreen_tokenIDListMouseClicked
        // TODO add your handling code here:
        loadTokenList();
        button_homescreen_validate.setEnabled(true);
    }//GEN-LAST:event_combo_homescreen_tokenIDListMouseClicked

    private void button_homescreen_sendReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_homescreen_sendReportActionPerformed
        // TODO add your handling code here:
        CaseReport newCaseReport = new CaseReport(reportID, inspectorID, tokenID, passengerID, station, calendar_date_time);
        if(CaseReportManager.addCaseReport(newCaseReport)){
            JOptionPane.showMessageDialog(null, "Case report " + reportID + " has been successfully submitted!", "Message", JOptionPane.INFORMATION_MESSAGE);
            disable_case_report_panel();
            button_homescreen_validate.setEnabled(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "Case report " + reportID + " NOT submitted correctly!", "Error", JOptionPane.ERROR_MESSAGE);
            button_homescreen_validate.setEnabled(false);
        }
    }//GEN-LAST:event_button_homescreen_sendReportActionPerformed

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        // TODO add your handling code here:
        boolean state = !jCheckBox1.isSelected();
        TokenValidator.status = state;
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void combo_homescreen_tokenIDListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_homescreen_tokenIDListActionPerformed
        // TODO add your handling code here:
        button_homescreen_validate.setEnabled(true);
    }//GEN-LAST:event_combo_homescreen_tokenIDListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InspectorTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InspectorTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InspectorTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InspectorTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new InspectorTerminal().setVisible(true);
                inspectorTerminal.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_homescreen_cancel;
    private javax.swing.JButton button_homescreen_logout;
    private javax.swing.JButton button_homescreen_profile;
    private javax.swing.JButton button_homescreen_sendReport;
    private javax.swing.JButton button_homescreen_validate;
    private javax.swing.JButton button_profiel_edit_done;
    private javax.swing.JButton button_profile_back;
    private javax.swing.JButton button_profile_edit;
    private javax.swing.JButton button_profile_edit_cancel;
    private javax.swing.JPanel case_report_panel;
    private javax.swing.JComboBox combo_homescreen_station;
    private javax.swing.JComboBox combo_homescreen_tokenIDList;
    private javax.swing.JComboBox combo_profile_edit_userGender;
    private javax.swing.JPanel homescreen_panel;
    private javax.swing.JButton jButton12;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_fixed_cashierID;
    private javax.swing.JLabel label_homescreen_currentUsername;
    private javax.swing.JLabel label_homescreen_date;
    private javax.swing.JLabel label_homescreen_inspectorID;
    private javax.swing.JLabel label_homescreen_passengerID;
    private javax.swing.JLabel label_homescreen_reportID;
    private javax.swing.JLabel label_homescreen_station;
    private javax.swing.JLabel label_homescreen_time;
    private javax.swing.JLabel label_homescreen_tokenID;
    private javax.swing.JLabel label_homescreen_tokenStatus;
    private javax.swing.JLabel label_inspectorID;
    private javax.swing.JLabel label_profile_userAddress;
    private javax.swing.JLabel label_profile_userContactNumber;
    private javax.swing.JLabel label_profile_userEmail;
    private javax.swing.JLabel label_profile_userGender;
    private javax.swing.JLabel label_profile_userName;
    private javax.swing.JPanel panel_tokenQRCode1;
    private javax.swing.JPanel panel_tokenQRCode2;
    private javax.swing.JPanel profile_edit_panel;
    private javax.swing.JPanel profile_panel;
    private javax.swing.JTextArea textArea_profile_edit_userAddress;
    private javax.swing.JTextField text_profile_edit_userContactNumber;
    private javax.swing.JTextField text_profile_edit_userEmail;
    private javax.swing.JTextField text_profile_edit_userName;
    private javax.swing.JPanel token_validator_panel;
    // End of variables declaration//GEN-END:variables

}
